# Generated by Django 6.0.2 on 2026-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('route_data', models.CharField(max_length=1000)),
            ],
        ),
    ]
