# Generated by Django 6.0.2 on 2026-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='stopsData',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_data',
            field=models.CharField(default=list),
        ),
    ]
