# Generated by Django 6.0.2 on 2026-02-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_routes_stopsdata_alter_routes_route_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('from_stop', models.CharField(max_length=100)),
                ('to_stop', models.CharField(max_length=100)),
                ('take_offs', models.JSONField(default=list)),
                ('returns', models.JSONField(default=list)),
            ],
        ),
    ]
