# Generated by Django 6.0.2 on 2026-02-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='timetable',
            field=models.JSONField(default=dict),
        ),
    ]
