# Generated by Django 6.0.2 on 2026-02-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0005_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('bus_stat', models.JSONField(default=list)),
            ],
        ),
    ]
