# Generated by Django 6.0.2 on 2026-02-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0006_workerupdates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerupdates',
            old_name='time',
            new_name='bus_name',
        ),
        migrations.RemoveField(
            model_name='workerupdates',
            name='bus_stat',
        ),
        migrations.AddField(
            model_name='workerupdates',
            name='live_location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='workerupdates',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
