# Generated by Django 6.0.2 on 2026-02-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0007_rename_time_workerupdates_bus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerupdates',
            name='live_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
