# Generated by Django 6.0.2 on 2026-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0008_alter_workerupdates_live_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerupdates',
            name='loaded_timetable',
            field=models.JSONField(default=list),
        ),
    ]
