# Generated by Django 6.0.2 on 2026-02-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0009_workerupdates_loaded_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerupdates',
            name='route_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
