# Generated by Django 6.0.2 on 2026-02-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0010_workerupdates_route_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='route_coords',
            field=models.JSONField(default=list, null=True),
        ),
    ]
