# Generated by Django 6.0.2 on 2026-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0011_routes_route_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('bus_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('current_stop', models.JSONField(default=list)),
                ('next_stop', models.JSONField(default=list)),
                ('live_location', models.JSONField(default=list)),
            ],
        ),
    ]
