# Generated by Django 6.0.2 on 2026-03-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0012_buslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCoords',
            fields=[
                ('route_name', models.CharField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=list)),
            ],
        ),
    ]
