# Generated by Django 6.0.2 on 2026-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0013_routecoords'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='stop_to_stop_coords',
            field=models.JSONField(default=list, null=True),
        ),
    ]
