# Generated by Django 6.0.2 on 2026-03-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0014_routes_stop_to_stop_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
