# Generated by Django 6.0.2 on 2026-03-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0015_buslocation_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='state',
            field=models.CharField(default='takeoff', max_length=50, null=True),
        ),
    ]
