# Generated by Django 6.0.2 on 2026-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0016_buslocation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='stop_index',
            field=models.IntegerField(null=True),
        ),
    ]
