# Generated by Django 6.0.2 on 2026-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0017_buslocation_stop_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='stop_change_time_indicator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
