# Generated by Django 6.0.2 on 2026-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0018_buslocation_stop_change_time_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='prev_stop_index',
            field=models.IntegerField(null=True),
        ),
    ]
