# Generated by Django 6.0.2 on 2026-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0019_buslocation_prev_stop_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='stop_change_time_indicator',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
