# Generated by Django 6.0.2 on 2026-03-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0020_alter_buslocation_stop_change_time_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='route_coords',
            field=models.JSONField(default=list, null=True),
        ),
    ]
