# Generated by Django 6.0.2 on 2026-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0021_buslocation_route_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='stop_to_stop_coords_rev',
            field=models.JSONField(default=None, null=True),
        ),
    ]
