# Generated by Django 6.0.2 on 2026-03-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0022_routes_stop_to_stop_coords_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='rev_coord_offset',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
