# Generated by Django 6.0.2 on 2026-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0023_buslocation_rev_coord_offset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buslocation',
            old_name='rev_coord_offset',
            new_name='rev_coord_end_offset',
        ),
        migrations.AddField(
            model_name='buslocation',
            name='rev_coord_start_offset',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
