# Generated by Django 6.0.2 on 2026-03-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0024_rename_rev_coord_offset_buslocation_rev_coord_end_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocation',
            name='processed_coord',
            field=models.JSONField(default=list, null=True),
        ),
    ]
