# Generated by Django 6.0.2 on 2026-03-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0025_buslocation_processed_coord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('passkey', models.CharField(max_length=100)),
            ],
        ),
    ]
