# Generated by Django 6.0.2 on 2026-03-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0026_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedBuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=100)),
            ],
        ),
    ]
