# Generated by Django 6.0.2 on 2026-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0027_assignedbuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerupdates',
            name='live_location_sharing_state',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
