# Generated by Django 6.0.2 on 2026-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0028_workerupdates_live_location_sharing_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerupdates',
            name='live_location_sharing_state',
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_is_sharing_location',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='live_location',
            field=models.JSONField(default=list, null=True),
        ),
    ]
