# Generated by Django 6.0.2 on 2026-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0029_remove_workerupdates_live_location_sharing_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='feedback_timetables',
            field=models.JSONField(default=list),
        ),
    ]
